# Generated by Django 4.2.13 on 2025-11-24 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_date', models.DateField()),
                ('employee_name', models.CharField(max_length=255)),
                ('from_site', models.CharField(max_length=255)),
                ('to_site', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('transfer_type', models.CharField(blank=True, choices=[('Month', 'Month'), ('Week', 'Week')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Transfer Entry',
                'verbose_name_plural': 'Site Transfer Entries',
                'ordering': ['-transfer_date', 'employee_name'],
            },
        ),
    ]
