# Generated by Django 4.2.13 on 2025-12-02 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0018_alter_employeeassetassignment_options_and_more'),
        ('entry', '0002_compoffentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(auto_now_add=True)),
                ('permission_date', models.DateField()),
                ('permission_start_time', models.TimeField(blank=True, null=True)),
                ('permission_end_time', models.TimeField(blank=True, null=True)),
                ('per_hr_count', models.DecimalField(decimal_places=2, default=0, help_text='Permission hours counted (e.g. 1.50 = 1 hour 30 minutes)', max_digits=6)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('cancelled', 'Cancel')], default='pending', max_length=20)),
                ('is_printed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permission_entries', to='master.employee')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permission_entries', to='master.site')),
            ],
            options={
                'verbose_name': 'Permission Entry',
                'verbose_name_plural': 'Permission Entries',
                'ordering': ['-permission_date', 'employee__staff_name'],
            },
        ),
    ]
