# Generated by Django 4.2.13 on 2025-12-02 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0020_add_document_to_expensetype'),
        ('entry', '0003_permissionentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(auto_now_add=True)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('leave_days', models.DecimalField(decimal_places=2, default=0, help_text='Number of leave days (e.g. 1.00 for full day, 0.50 for half day)', max_digits=5)),
                ('leave_type', models.CharField(choices=[('compensatory-leave', 'Compensatory Leave/Off'), ('earned-leave', 'Earned Leave'), ('LOP', 'Loss of Pay'), ('Sick-leave', 'Sick Leave'), ('casual-leave', 'Casual Leave')], max_length=50)),
                ('leave_duration_type', models.CharField(choices=[('full_day', 'Full day'), ('forenoon', 'Forenoon'), ('afternoon', 'Afternoon')], default='full_day', max_length=20)),
                ('reason', models.TextField()),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('staff_approved', 'Staff Approved'), ('hr_approved', 'HR Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approved_by', models.CharField(blank=True, max_length=255)),
                ('approval_note', models.CharField(blank=True, max_length=255)),
                ('is_printed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_entries', to='master.employee')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_entries', to='master.site')),
            ],
            options={
                'verbose_name': 'Leave Entry',
                'verbose_name_plural': 'Leave Entries',
                'ordering': ['-from_date', 'employee__staff_name'],
            },
        ),
    ]
