# Generated by Django 4.2.13 on 2025-12-04 08:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0021_add_shift_roster_models'),
        ('entry', '0004_leaveentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='TADAEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(auto_now_add=True)),
                ('expense_date', models.DateField()),
                ('entry_no', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('batch_no', models.CharField(blank=True, max_length=50)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('head_approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('hr_approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('acc_approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('is_printed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tada_entries', to='master.employee')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tada_entries', to='master.site')),
            ],
            options={
                'verbose_name': 'TADA Entry',
                'verbose_name_plural': 'TADA Entries',
                'ordering': ['-expense_date', '-entry_date', 'employee__staff_name'],
            },
        ),
        migrations.AlterField(
            model_name='siteentry',
            name='transfer_type',
            field=models.CharField(blank=True, choices=[('Month', 'Month'), ('Week', 'Week')], max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='TADAEntrySubItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_location', models.CharField(max_length=255)),
                ('to_location', models.CharField(max_length=255)),
                ('start_meter', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('end_meter', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_kilometer', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('upload_image', models.ImageField(blank=True, null=True, upload_to='tada_entry/images/')),
                ('meter_upload_image', models.ImageField(blank=True, null=True, upload_to='tada_entry/meter_images/')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expense_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tada_sub_items', to='master.expensetype')),
                ('sub_expense_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tada_sub_items', to='master.subexpense')),
                ('tada_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_items', to='entry.tadaentry')),
            ],
            options={
                'verbose_name': 'TADA Entry Sub Item',
                'verbose_name_plural': 'TADA Entry Sub Items',
                'ordering': ['created_at'],
            },
        ),
    ]
