# Generated by Django 4.2.13 on 2025-12-05 07:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0005_tadaentry_alter_siteentry_transfer_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tadaentry',
            name='head_approval_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount approved by head (can be different from total_amount)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
