# Generated by Django 4.2.13 on 2025-12-05 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0006_tadaentry_head_approval_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='tadaentry',
            name='head_approval_by',
            field=models.CharField(blank=True, help_text='Name of the person who approved/rejected', max_length=255),
        ),
        migrations.AddField(
            model_name='tadaentry',
            name='head_approval_date',
            field=models.DateTimeField(blank=True, help_text='Date and time of head approval', null=True),
        ),
    ]
