# Generated by Django 4.2.13 on 2025-12-05 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0007_tadaentry_head_approval_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tadaentry',
            name='hr_approval_by',
            field=models.CharField(blank=True, help_text='Name of the person who approved/rejected at HR level', max_length=255),
        ),
        migrations.AddField(
            model_name='tadaentry',
            name='hr_approval_date',
            field=models.DateTimeField(blank=True, help_text='Date and time of HR approval', null=True),
        ),
    ]
