# Generated by Django 4.2.13 on 2025-12-05 13:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0021_add_shift_roster_models'),
        ('entry', '0008_tadaentry_hr_approval_by_tadaentry_hr_approval_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(auto_now_add=True)),
                ('travel_mode', models.CharField(choices=[('bus', 'Bus'), ('train', 'Train'), ('cab', 'Cab'), ('flight', 'Flight')], max_length=20)),
                ('trip_type', models.CharField(choices=[('one_way', 'One Way'), ('return', 'Return')], default='one_way', max_length=20)),
                ('booking_option', models.CharField(choices=[('front_desk', 'Front Desk'), ('self', 'Self')], max_length=20)),
                ('accommodation_type', models.CharField(blank=True, choices=[('hotel', 'Hotel'), ('guest_house', 'Guest House')], max_length=20)),
                ('from_location', models.CharField(max_length=255)),
                ('to_location', models.CharField(max_length=255)),
                ('departure_date', models.DateField()),
                ('departure_time', models.TimeField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('return_time', models.TimeField(blank=True, null=True)),
                ('no_of_days', models.IntegerField(help_text='Number of days for travel', validators=[django.core.validators.MinValueValidator(1)])),
                ('travel_reason', models.CharField(choices=[('business_trip', 'Business Trip'), ('home_town_visit', 'Quarterly Home Town Visit')], max_length=50)),
                ('purpose_of_visit', models.TextField()),
                ('aadhar_upload', models.ImageField(blank=True, null=True, upload_to='travel_entry/aadhar/')),
                ('one_way_document', models.ImageField(blank=True, null=True, upload_to='travel_entry/documents/')),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approved_by', models.CharField(blank=True, max_length=255)),
                ('approval_note', models.CharField(blank=True, max_length=255)),
                ('is_printed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='travel_entries', to='master.employee')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='travel_entries', to='master.site')),
            ],
            options={
                'verbose_name': 'Travel Requisition Entry',
                'verbose_name_plural': 'Travel Requisition Entries',
                'ordering': ['-departure_date', '-entry_date', 'employee__staff_name'],
            },
        ),
    ]
