# Generated by Django 4.2.13 on 2025-12-06 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0021_add_shift_roster_models'),
        ('entry', '0009_travelentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField()),
                ('salary_type', models.CharField(choices=[('salary', 'Salary'), ('wages', 'Wages'), ('others', 'Others')], max_length=20)),
                ('shift_type', models.CharField(choices=[('day_shift', 'Day Shift'), ('night_shift', 'Night Shift'), ('rotational_shift', 'Rotational Shift')], max_length=30)),
                ('shift_in_time', models.TimeField(blank=True, null=True)),
                ('shift_out_time', models.TimeField(blank=True, null=True)),
                ('attendance_type', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('half_day', 'Half Day'), ('leave', 'Leave')], default='present', max_length=20)),
                ('remarks', models.TextField(blank=True, help_text='Additional remarks or notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manual_entries', to='master.employee')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manual_entries', to='master.site')),
            ],
            options={
                'verbose_name': 'Manual Attendance Entry',
                'verbose_name_plural': 'Manual Attendance Entries',
                'ordering': ['-attendance_date', 'employee__staff_name'],
                'unique_together': {('attendance_date', 'employee', 'site')},
            },
        ),
    ]
