# Generated by Django 4.2.13 on 2025-12-06 07:37

from django.db import migrations, models
import django.db.models.deletion
from django.db import connection


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0021_add_shift_roster_models'),
        ('entry', '0010_manualentry'),
    ]

    operations = [
        # Remove shift_type only if it exists
        migrations.RunSQL(
            """
            SET @exist := (SELECT COUNT(*) FROM information_schema.columns 
                          WHERE table_schema = DATABASE() 
                          AND table_name = 'entry_manualentry' 
                          AND column_name = 'shift_type');
            SET @sqlstmt := IF(@exist > 0, 'ALTER TABLE entry_manualentry DROP COLUMN shift_type', 'SELECT 1');
            PREPARE stmt FROM @sqlstmt;
            EXECUTE stmt;
            DEALLOCATE PREPARE stmt;
            """,
            reverse_sql=migrations.RunSQL.noop,
            state_operations=[
                migrations.RemoveField(
                    model_name='manualentry',
                    name='shift_type',
                ),
            ]
        ),
        migrations.RunSQL(
            """
            SET @exist := (SELECT COUNT(*) FROM information_schema.columns 
                          WHERE table_schema = DATABASE() 
                          AND table_name = 'entry_manualentry' 
                          AND column_name = 'shift_id');
            SET @sqlstmt := IF(@exist = 0, 
                'ALTER TABLE entry_manualentry ADD COLUMN shift_id INT NULL, ADD CONSTRAINT entry_manualentry_shift_id_fk FOREIGN KEY (shift_id) REFERENCES master_shift(id) ON DELETE RESTRICT',
                'SELECT 1');
            PREPARE stmt FROM @sqlstmt;
            EXECUTE stmt;
            DEALLOCATE PREPARE stmt;
            """,
            reverse_sql=migrations.RunSQL.noop,
            state_operations=[
                migrations.AddField(
                    model_name='manualentry',
                    name='shift',
                    field=models.ForeignKey(blank=True, help_text='Shift from master data', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manual_entries', to='master.shift'),
                ),
            ]
        ),
        migrations.AlterField(
            model_name='leaveentry',
            name='leave_type',
            field=models.ForeignKey(blank=True, help_text='Leave type from master data', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leave_entries', to='master.leavetype'),
        ),
        migrations.AlterField(
            model_name='manualentry',
            name='salary_type',
            field=models.ForeignKey(blank=True, help_text='Salary type from master data', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manual_entries', to='master.salarytype'),
        ),
    ]
