# Generated by Django 4.2.13 on 2025-12-01 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entry', '0002_compoffentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approval_note', models.TextField(blank=True)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travel_approvals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Travel Approval',
                'verbose_name_plural': 'Travel Approvals',
                'ordering': ['-created_at'],
                'permissions': [('view_travel_approval', 'Can view Travel Approvals'), ('approve_travel_approval', 'Can approve Travel Approvals')],
            },
        ),
        migrations.CreateModel(
            name='TADAApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approval_note', models.TextField(blank=True)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tada_approvals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TADA Approval',
                'verbose_name_plural': 'TADA Approvals',
                'ordering': ['-created_at'],
                'permissions': [('view_tada_approval', 'Can view TADA Approvals'), ('approve_tada_approval', 'Can approve TADA Approvals')],
            },
        ),
        migrations.CreateModel(
            name='PermissionApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approval_note', models.TextField(blank=True)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permission_approvals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permission Approval',
                'verbose_name_plural': 'Permission Approvals',
                'ordering': ['-created_at'],
                'permissions': [('view_permission_approval', 'Can view Permission Approvals'), ('approve_permission_approval', 'Can approve Permission Approvals')],
            },
        ),
        migrations.CreateModel(
            name='LeaveApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approval_note', models.TextField(blank=True)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_approvals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Leave Approval',
                'verbose_name_plural': 'Leave Approvals',
                'ordering': ['-created_at'],
                'permissions': [('view_leave_approval', 'Can view Leave Approvals'), ('approve_leave_approval', 'Can approve Leave Approvals')],
            },
        ),
        migrations.CreateModel(
            name='HRCompOffApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hr_approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('hr_approval_note', models.TextField(blank=True, help_text='Notes or comments from HR')),
                ('hr_approval_date', models.DateTimeField(blank=True, help_text='Date and time of HR approval', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comp_off_entry', models.OneToOneField(help_text='The Comp-Off Entry being approved', on_delete=django.db.models.deletion.CASCADE, related_name='hr_approval', to='entry.compoffentry')),
                ('hr_approval_by', models.ForeignKey(blank=True, help_text='HR user who approved/rejected', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_comp_off_approvals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'HR Comp-Off Approval',
                'verbose_name_plural': 'HR Comp-Off Approvals',
                'ordering': ['-created_at'],
                'permissions': [('view_hr_compoff_approval', 'Can view HR Comp-Off Approvals'), ('approve_hr_compoff_approval', 'Can approve HR Comp-Off Approvals'), ('reject_hr_compoff_approval', 'Can reject HR Comp-Off Approvals')],
            },
        ),
    ]
