# Generated by Django 4.2.13 on 2025-12-02 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0004_leaveentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('approval', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapproval',
            name='leave_entry',
            field=models.OneToOneField(blank=True, help_text='The Leave Entry being approved', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_approval', to='entry.leaveentry'),
        ),
        migrations.AlterField(
            model_name='leaveapproval',
            name='approval_date',
            field=models.DateTimeField(blank=True, help_text='Date and time of approval', null=True),
        ),
        migrations.AlterField(
            model_name='leaveapproval',
            name='approval_note',
            field=models.TextField(blank=True, help_text='Notes or comments from approver'),
        ),
        migrations.AlterField(
            model_name='leaveapproval',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='User who approved/rejected', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_approvals', to=settings.AUTH_USER_MODEL),
        ),
    ]
