# Generated by Django 4.2.13 on 2025-12-06 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0009_travelentry'),
        ('approval', '0002_leaveapproval_leave_entry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelapproval',
            name='travel_entry',
            field=models.OneToOneField(blank=True, help_text='The Travel Entry being approved', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='travel_approval', to='entry.travelentry'),
        ),
    ]
