# Generated by Django 4.2.13 on 2025-11-07 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_group', models.CharField(max_length=150)),
                ('address', models.TextField()),
                ('billing_name', models.CharField(max_length=150)),
                ('billing_address', models.TextField()),
                ('mobile_no', models.CharField(max_length=20)),
                ('phone_no', models.CharField(blank=True, max_length=20)),
                ('gstin_no', models.CharField(max_length=30, unique=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['company_group', 'billing_name'],
            },
        ),
    ]
