# Generated by Django 4.2.13 on 2025-11-08 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_degree'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='degree',
            options={'ordering': ['education_type', 'name']},
        ),
        migrations.RemoveField(
            model_name='degree',
            name='description',
        ),
        migrations.RemoveField(
            model_name='degree',
            name='status',
        ),
        migrations.AddField(
            model_name='degree',
            name='education_type',
            field=models.CharField(choices=[('UG', 'UG'), ('PG', 'PG'), ('TECH', 'Technical Education'), ('HSC', 'HSC'), ('SSLC', 'SSLC')], default='UG', max_length=10),
        ),
    ]
