# Generated by Django 4.2.13 on 2025-11-20 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0008_assettype'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('image_required', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='assettype',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
