# Generated by Django 4.2.13 on 2025-11-21 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0011_leavetype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavetype',
            name='is_active',
        ),
    ]
