# Generated by Django 4.2.13 on 2025-11-21 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0012_remove_leavetype_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Addition', 'Addition'), ('Deduction', 'Deduction')], max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Addition and Deduction',
                'verbose_name_plural': 'Additions and Deductions',
                'ordering': ['type', 'name'],
                'unique_together': {('type', 'name')},
            },
        ),
    ]
