# Generated by Django 4.2.13 on 2025-11-21 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0013_additiondeduction'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField()),
                ('name', models.CharField(max_length=150)),
                ('image_required', models.BooleanField(default=False)),
                ('image_type', models.CharField(blank=True, choices=[('Common Image', 'Common Image'), ('Start and End Meter Image', 'Start and End Meter Image')], max_length=50)),
                ('meter_type', models.CharField(blank=True, choices=[('Start and End Meter', 'Start and End Meter'), ('Total Kilometer', 'Total Kilometer')], max_length=50)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expense_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_expenses', to='master.expensetype')),
            ],
            options={
                'verbose_name': 'Sub Expense',
                'verbose_name_plural': 'Sub Expenses',
                'ordering': ['-entry_date', 'expense_type__name', 'name'],
                'unique_together': {('expense_type', 'name')},
            },
        ),
    ]
