# Generated by Django 4.2.13 on 2025-12-01 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0017_employee_employeevehicledetail_employeequalification_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeassetassignment',
            options={'ordering': ['employee', '-created_at'], 'verbose_name': 'Employee Asset Assignment', 'verbose_name_plural': 'Employee Asset Assignments'},
        ),
        migrations.AddField(
            model_name='employeeassetassignment',
            name='asset_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='master.assettype'),
        ),
        migrations.AddField(
            model_name='employeeassetassignment',
            name='description',
            field=models.TextField(blank=True, help_text='Additional notes or description'),
        ),
        migrations.AddField(
            model_name='employeeassetassignment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='employeeassetassignment',
            name='asset_name',
            field=models.CharField(blank=True, help_text='Legacy field - use asset_type instead', max_length=255),
        ),
        migrations.AlterField(
            model_name='employeeassetassignment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_assignments', to='master.employee'),
        ),
    ]
