# Generated by Django 4.2.13 on 2025-11-07 04:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(blank=True, max_length=30)),
                ('job_title', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('date_of_joining', models.DateField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=20)),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('permanent_address', models.TextField(blank=True)),
                ('emergency_number', models.CharField(blank=True, max_length=20)),
                ('blood_group', models.CharField(blank=True, max_length=10)),
                ('aadhar_number', models.CharField(blank=True, max_length=30)),
                ('pan_number', models.CharField(blank=True, max_length=20)),
                ('esi_number', models.CharField(blank=True, max_length=30)),
                ('pf_number', models.CharField(blank=True, max_length=30)),
                ('uan_number', models.CharField(blank=True, max_length=30)),
                ('communication_address', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
