# Generated by Django 4.2.13 on 2025-12-02 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account_verified',
            field=models.BooleanField(default=False, help_text='Whether the employee has verified their account'),
        ),
        migrations.AddField(
            model_name='profile',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='Force user to change password on next login'),
        ),
        migrations.AddField(
            model_name='profile',
            name='verification_token',
            field=models.CharField(blank=True, help_text='Token for account verification', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='verification_token_expires',
            field=models.DateTimeField(blank=True, help_text='Expiration time for verification token', null=True),
        ),
    ]
